// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://urogttyhfqerukpuxnwj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVyb2d0dHloZnFlcnVrcHV4bndqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwNjgyMjYsImV4cCI6MjA2OTY0NDIyNn0.fRn9vcEDFt47asr6KUWwuXBXhQ9oP6w5UD4DUGtGmpQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});